# Generated by Django 4.2.13 on 2026-07-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bitrix24_deal_id',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='ID сделки в Битрикс24'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('awaiting_payment', 'Ожидает оплаты'), ('created', 'Оформлен'), ('collecting', 'Комплектуется'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], max_length=20, null=True, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован в банке'), ('pending', 'Ожидает оплаты'), ('authorized', 'Авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонён'), ('canceled', 'Отменён'), ('refunded', 'Возврат'), ('error', 'Ошибка')], default='registered', max_length=15, verbose_name='Статус платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма (₽)')),
                ('alfa_order_id', models.CharField(blank=True, db_index=True, max_length=63, null=True, verbose_name='ID заказа в банке')),
                ('form_url', models.URLField(blank=True, max_length=1023, null=True, verbose_name='Ссылка на оплату')),
                ('error_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('raw_register_response', models.JSONField(blank=True, null=True, verbose_name='Ответ банка (register)')),
                ('raw_status_response', models.JSONField(blank=True, null=True, verbose_name='Ответ банка (status)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения оплаты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
