# Generated by Django 4.2.13 on 2026-08-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_bitrix24_deal_id_alter_order_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('awaiting_payment', 'Ожидает оплаты'), ('created', 'Оформлен'), ('collecting', 'Комплектуется'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('canceled', 'Отменен'), ('payment_failed', 'Ошибка оплаты'), ('payment_canceled', 'Оплата отменена'), ('refunded', 'Возврат')], max_length=20, null=True, verbose_name='Статус заказа'),
        ),
    ]
