from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import galleryfield.fields
import sortedm2m.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('attr_type', models.CharField(choices=[('string', 'строка'), ('int', 'целое число'), ('float', 'дробное число')], default='string', max_length=7, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, max_length=7, verbose_name='Единица измерения')),
                ('with_options', models.BooleanField(default=False, verbose_name='Выбор из вариантов')),
                ('id_1c', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID в 1C')),
                ('is_synced_with_1c', models.BooleanField(default=False, verbose_name='Синхронизовано с 1C')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta title (заголовок страницы)')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta description (описание страницы)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta keywords (ключевые слова через запятую)')),
                ('seo_text', tinymce.models.HTMLField(blank=True, verbose_name='SEO-текст')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Адрес в url')),
                ('logo', models.FileField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Логотип')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='brands/photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, help_text='\n            оставьте пустым, чтобы использовать стандартное описание:\n            <br/>\n            «Метатэкс изготавливает навесное оборудование, совместимое со спецтехникой марки <Название бренда>»\n        ', verbose_name='Краткое описание')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'бренд техники',
                'verbose_name_plural': 'бренды техники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta title (заголовок страницы)')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta description (описание страницы)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta keywords (ключевые слова через запятую)')),
                ('seo_text', tinymce.models.HTMLField(blank=True, verbose_name='SEO-текст')),
                ('name', models.CharField(help_text='пример: «Для фронтальных погрузчиков»', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Адрес в url')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='файл .png', null=True, upload_to='categories/icons/', verbose_name='Иконка')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='categories/covers/', verbose_name='Обложка')),
                ('name_single', models.CharField(blank=True, help_text='пример: «для фронтального погрузчика»', max_length=255, verbose_name='Название (в единственном числе)')),
                ('name_product', models.CharField(blank=True, help_text='пример: «на фронтальный погрузчик»', max_length=255, verbose_name='Название (на странице товара)')),
                ('price_list', models.FileField(blank=True, null=True, upload_to='categories/price_lists/', verbose_name='Файл с прайсом')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('id_1c', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID в 1C')),
                ('is_synced_with_1c', models.BooleanField(default=False, verbose_name='Синхронизовано с 1C')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': '1) Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta title (заголовок страницы)')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta description (описание страницы)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta keywords (ключевые слова через запятую)')),
                ('seo_text', tinymce.models.HTMLField(blank=True, verbose_name='SEO-текст')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Адрес в url')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/photos/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена, руб.')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('tech_description', models.FileField(blank=True, null=True, upload_to='products/tech/', verbose_name='Техническое описание')),
                ('gallery', galleryfield.fields.GalleryField(blank=True, help_text='до 5 фото', null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='Фотогалерея')),
                ('gallery_3d', galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='3D-галерея')),
                ('attrs', models.JSONField(default=dict)),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Показывать в списке «Популярное»')),
                ('id_1c', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID в 1C')),
                ('is_synced_with_1c', models.BooleanField(default=False, verbose_name='Синхронизовано с 1C')),
                ('bar_code', models.CharField(blank=True, max_length=15, verbose_name='Штрихкод')),
                ('vendor_code', models.CharField(blank=True, max_length=15, verbose_name='Артикул')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': '3) Товары',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta title (заголовок страницы)')),
                ('meta_description', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta description (описание страницы)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать поле "Заголовок"', max_length=255, verbose_name='Meta keywords (ключевые слова через запятую)')),
                ('seo_text', tinymce.models.HTMLField(blank=True, verbose_name='SEO-текст')),
                ('name', models.CharField(help_text='пример: «Ковши общего назначения»', max_length=255, verbose_name='Название')),
                ('name_single', models.CharField(blank=True, help_text='пример: «ковш общего назначения»', max_length=255, verbose_name='Название (в единственном числе)')),
                ('slug', models.SlugField(verbose_name='Адрес в url')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='models/photos/', verbose_name='Обложка')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('design_features_title', models.CharField(default='Конструктивные особенности', help_text='пример: «Конструктивные особенности ковша общего назначения»', max_length=255, verbose_name='Конструктивные особенности: заголовок')),
                ('design_features', tinymce.models.HTMLField(blank=True, verbose_name='Конструктивные особенности: текст')),
                ('construction_features', tinymce.models.HTMLField(blank=True, verbose_name='Особенности конструкции')),
                ('attributes_table', tinymce.models.HTMLField(blank=True, verbose_name='Таблица с характеристиками')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Показывать в списке «Популярное»')),
                ('id_1c', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID в 1C')),
                ('is_synced_with_1c', models.BooleanField(default=False, verbose_name='Синхронизовано с 1C')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('attributes', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='sub_categories', to='catalog.attribute', verbose_name='Характеристики')),
                ('attributes_in_filter', sortedm2m.fields.SortedManyToManyField(blank=True, help_text='не больше 1 характеристики', related_name='filter_sub_categories', to='catalog.attribute', verbose_name='Характеристики в фильтре')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': '2) Подкатегории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('video', models.URLField(blank=True, help_text='ссылка на youtube.com', null=True, verbose_name='Видео')),
                ('video_id', models.CharField(blank=True, editable=False, max_length=31, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание (необязательно)')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('show_on_subcategory', models.BooleanField(default=True, verbose_name='Показывать на странице подкатегории')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'товары: видео',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('value', models.CharField(max_length=127, verbose_name='Значение')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'реквизит',
                'verbose_name_plural': 'товары: реквизиты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/photos/', verbose_name='Фото')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('show_on_subcategory', models.BooleanField(default=True, verbose_name='Показывать на странице подкатегории')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'товары: фото',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('value_string', models.CharField(blank=True, max_length=31, null=True, verbose_name='Значение (строка)')),
                ('value_int', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Значение (целое число)')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='Значение (дробное число)')),
                ('id_1c', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID в 1C')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attribute', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'вариант',
                'verbose_name_plural': 'характеристики: варианты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена, руб.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_products', to='catalog.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'дополнительный товар',
                'verbose_name_plural': 'дополнительные товары',
                'ordering': ['-is_active', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='catalog.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='addresses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'количество на складе',
                'verbose_name_plural': 'товары: количество на складе',
                'ordering': ['warehouse'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
