# Generated by Django 4.2.13 on 2026-04-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_subcategory_card_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_in_stock', 'order'], 'verbose_name': 'товар', 'verbose_name_plural': '4) Товары'},
        ),
    ]
